services:
  app:
    build:
      context: .
      dockerfile: environment/Dockerfile.prod
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "9000:9000"
    environment:
      - ROLE=app
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=coinapp
      - DB_USERNAME=coinuser
      - DB_PASSWORD=secret
    depends_on:
      - postgres
      - redis
    command: ["sh", "/entrypoint.sh"]

  queue:
    build:
      context: .
      dockerfile: environment/Dockerfile.prod
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - ROLE=queue
    depends_on:
      - app
    command: ["sh", "/entrypoint.sh"]

  scheduler:
    build:
      context: .
      dockerfile: environment/Dockerfile.prod
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - ROLE=scheduler
    depends_on:
      - app
    command: ["sh", "/entrypoint.sh"]

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: coinapp
      POSTGRES_USER: coinuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
