services:
  app:
    build:
      context: .
      dockerfile: environment/Dockerfile.prod
    container_name: coinapp_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=production
    env_file:
      - .env.production
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: coinapp_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: coinapp_postgres
    environment:
      POSTGRES_DB: coinapp
      POSTGRES_USER: coinuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:alpine
    container_name: coinapp_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          memory: 256M

  queue:
    build:
      context: .
      dockerfile: environment/Dockerfile.prod
    container_name: coinapp_queue
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env.production
    environment:
      - ROLE=queue
    depends_on:
      - app
    command: ["sh", "/entrypoint.prod.sh"]
    deploy:
      resources:
        limits:
          memory: 256M

  scheduler:
    build:
      context: .
      dockerfile: environment/Dockerfile.prod
    container_name: coinapp_scheduler
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env.production
    environment:
      - ROLE=scheduler
    depends_on:
      - app
    command: ["sh", "/entrypoint.prod.sh"]
    deploy:
      resources:
        limits:
          memory: 256M

  mailpit:
    image: axllent/mailpit
    container_name: coinapp_mailpit
    ports:
      - "8025:8025"
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  pgdata:
  redisdata:
