services:
  app:
    build:
      context: .
      dockerfile: environment/Dockerfile.prod
    container_name: app
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    environment:
      - ROLE=app
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=coinapp
      - DB_USERNAME=coinuser
      - DB_PASSWORD=secret
    depends_on:
      - postgres
      - redis
    command: ["/entrypoint.prod.sh"]
    volumes:
      - ./entrypoint.prod.sh:/entrypoint.prod.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/html/public
      - ./src/storage:/var/www/html/storage
    depends_on:
      app:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: coinapp
      POSTGRES_USER: coinuser
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: