services:
  app:
    build:
      context: .
      dockerfile: environment/Dockerfile.dev
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "9000:9000"
    environment:
      - ROLE=app
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=coinapp
      - DB_USERNAME=coinuser
      - DB_PASSWORD=secret
    depends_on:
      - postgres
      - redis
    command: ["/entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  vite:
    image: node:18-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

  queue:
    build:
      context: .
      dockerfile: environment/Dockerfile.dev
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - ROLE=queue
    depends_on:
      - app
    command: ["/entrypoint.sh"]

  scheduler:
    build:
      context: .
      dockerfile: environment/Dockerfile.dev
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - ROLE=scheduler
    depends_on:
      - ap
