FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git curl unzip zip nodejs npm \
    libpq-dev libzip-dev libpng-dev \
    libonig-dev libxml2-dev \
    netcat-openbsd \
    && docker-php-ext-install pdo pdo_pgsql zip \
    && pecl install redis \
    && docker-php-ext-enable redis

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY ./src ./

RUN composer install
RUN npm install

CMD ["php-fpm"]
